name: Build VM Image

on: [push]

jobs:
  build-image:
    runs-on: ubuntu-18.04
    name: Build VM Image

    steps:
      - name: Install VirtualBox
        run: wget -q https://download.virtualbox.org/virtualbox/6.1.16/virtualbox-6.1_6.1.16-140961~Ubuntu~bionic_amd64.deb | sudo apt-get install -

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: playground.json

      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: playground.json
